### ISSUE TITLE
Import not working on Google Colab

### ISSUE THREAD

**Issue by jhjensen2** [akensert/molgraph#30]
After pip installing MolGraph on Google Colab I get the following error from `from molgraph import layers`:

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
Cell In[1], line 6
      2 os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
      4 from pathlib import Path
----> 6 from molgraph import layers
      7 from molgraph import chemistry
      8 import tensorflow as tf

File /usr/local/lib/python3.11/dist-packages/molgraph/__init__.py:35
     33 from molgraph import metrics
     34 from molgraph import models
---> 35 from molgraph import chemistry
     37 from molgraph.tensors import GraphTensor

ImportError: cannot import name 'chemistry' from partially initialized module 'molgraph' (most likely due to a circular import) (/usr/local/lib/python3.11/dist-packages/molgraph/__init__.py)
```

[Link to notebook](https://colab.research.google.com/drive/1XqL2QJruQb3kkD1Z9tMwVEWmuEoob-lG?usp=sharing)

**Comment by akensert** [comment]
@jhjensen2 Thanks for letting me know. I'll look into it!

**Comment by akensert** [comment]
It appeared in 0.8.1 it seems, and I cannot see where the issue is. Also, I cannot replicate this error locally.

**Comment by jhjensen2** [comment]
Ah, OK. I'll use 0.8.0 then. Thanks for looking in to it.

**Comment by akensert** [comment]
@jhjensen2 No problem, but I'll try to figure it out. 0.8.1 had an important fix for 3D molecular graphs (in MolecularGraphEncoder3D).

**Comment by akensert** [comment]
Seems like it was not fixed, I'll work on it again and bump to 0.10.0.

**Comment by jhjensen2** [comment]
Works for me too. Thanks!
